kind: pipeline
type: docker
name: gen-images

platform:
  os: linux
  arch: amd64

steps:
  - name: build-backend
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DB_URL: 
        from_secret: DB_URL
    dockerfile: ./Dockerfile.backend

trigger:
  branch:
    - main
