kind: pipeline
type: docker
name: gen-images

platform:
  os: linux
  arch: amd64

steps:
  - name: build-backend
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DB_URL: 
        from_secret: DB_URL
    settings:
      build_args_from_env:
        - DB_URL
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_PASSWORD
      repo:
        from_secret: DOCKER_HUB_REPO
      tags: latest
      dockerfile: ./Dockerfile.backend
    when:
      paths:
        include:
          - backend/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
