kind: pipeline
type: docker
name: gen-images

steps:
  - name: build-backend
    image: plugins/docker
    environment:
      DB_URL: 
        from_secret: DB_URL
    commands:
      - docker build -t backend-flask -f Dockerfile.backend .

trigger:
  branch:
    - main
