kind: pipeline
type: docker
name: gen-images

platform:
  os: linux
  arch: amd64

steps:
  - name: build-backend
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DB_URL: 
        from_secret: DB_URL
    settings:
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_PASSWORD
      repo:
        from_secret: DOCKER_HUB_REPO
      tags: 0.0.1
      dockerfile: ./Dockerfile.backend

trigger:
  branch:
    - main
