FROM python:latest

ARG DB_URL
ENV DB_URL $DB_URL

RUN useradd -m -s /bin/bash python
USER python
WORKDIR /home/python
COPY backend/ /home/python
RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
